site_name: ssh usefull codes


theme:
  name: material
  language: ru
  features:
#    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
#    - toc.integrate

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

  plugins:
    - social

  extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/james-willett
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/TheJamesWillett
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/willettjames/
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2024 settings-django-nginx
